//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage1 { get; set; }
        public string ProductImage2 { get; set; }
        public string ProductImage3 { get; set; }
        public bool ProductAvailability { get; set; }
        public System.DateTime RentStartDate { get; set; }
        public System.DateTime RentEndDate { get; set; }
        public int CategoryId { get; set; }
        public double ProductUnitPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
